do not overwrite @timestamp in data stream if it already exists in the record
uken/fluent-plugin-elasticsearch pull request #968
Opened 2022-04-21 16:10 UTC by dschaaff

DESCRIPTION HERE

(check all that apply)
- [ ] tests added
- [ ] tests passing
- [ ] README updated (if needed)
- [ ] README Table of Contents updated (if needed)
- [ ] History.md and `version` in gemspec are untouched
- [ ] backward compatible
- [ ] feature works in `elasticsearch_dynamic` (not required but recommended)

2022-05-10 05:19 UTC, cosmo0920 requested changes
Could you add a testcase for this change?

2022-05-17 23:24 UTC, dschaaff commented
@cosmo0920 I'll look into adding a test.

2022-05-20 16:25 UTC, dschaaff commented
@cosmo0920 I've added a test if you don't mind reviewing when you have time. Thanks!

2022-05-23 02:18 UTC, cosmo0920 approved these changes
Looks good. Thanks for your work!

2022-05-23 03:03 UTC, merged